services:
  db:
    container_name: db
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: shokuyou
      MONGO_INITDB_ROOT_PASSWORD: shokuyou
    ports:
      - 27017:27017
